export const enum UserErrors {
  DISPLAY_NAME_TOO_LONG = 'DISPLAY_NAME_TOO_LONG',
  DISPLAY_NAME_TOO_SHORT = 'DISPLAY_NAME_TOO_SHORT',

  PASSWORD_TOO_LONG = 'PASSWORD_TOO_LONG',
  PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
}
