export const enum TransactionError {
  INVALID_TRANSACTION = 'INVALID_TRANSACTION',
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  TRANSACTION_ALREADY_EXISTS = 'TRANSACTION_ALREADY_EXISTS',

  INVALID_TAG = 'INVALID_TAG',
  TAG_NOT_FOUND = 'TAG_NOT_FOUND',
  TAG_ALREADY_EXISTS = 'TAG_ALREADY_EXISTS',
}
